### ISSUE TITLE
[request] add node.stripLength

### ISSUE THREAD

**Issue by arnaudjuracek** [Hemisphere-Project/stratum-hnode#2]
Ça serait pratique de pouvoir connaître le nombre de strip branchées sur un node, pour pouvoir gérer le mapping correctement 👍

**Comment by arnaudjuracek** [comment]
Mieux en fait, pouvoir récupérer un array de bool pour savoir quelles prises sont branchées : `node.strips = [true, true, false, true]`. Le nombre de strip branchées peut-être déduit de cet array.

**Comment by Maigre** [comment]
La communication est unidirectionnelle,
électroniquement il n'y a pas de retour d'info.
Je vais réfléchir pour voir si il y a une astuce mais à priori comme ça je
ne vois pas trop..

**Comment by arnaudjuracek** [comment]
Peut-être en faisant un test de continuité sur des broches dispo du RJ ? L'idée c'est vraiment d'avoir une info de branché/débranché, pour faciliter le mapping (et la gestion des nodes < 4 strips).

Mais si ça te semble trop compliqué à mettre en place sur 4x23 RJ, je trouverais une astuce sur la GUI pour que ça soit l'utilisateur qui entre l'info.

**Comment by Maigre** [comment]
J'utilise déjà les 8 pins du RJ:
1x data  / 3x 5V / 4x GND
On aurait probablement pu utiliser une de moins pour le GND et faire avec
mais j'ai envoyé l'impression d'un proto de PCB hier du coup c'est un peu
galère de retoucher le câblage..
D'autre part je n'ai plus beaucoup de pin dispo pour ça sur le
microcontrolleur.
Enfin la section de cable est un peu légère,  du coup c'est un peu risqué
de se priver d'un conducteur: l'alim est déjà poussée à 6,5v pour obtenir
du 5v au niveau des bandeaux lors de l'allumage complet.

Je vais refaire le compte et voir si je peux effectivement recabler ça sur
le PCB sans trop risquer de le compromettre car il n'y aura pas le temps de
faire un autre proto (ou pour un coût qui ne vaut pas le coup).
Mais l'idée est bonne, bien que ça risque d'être un peu juste à rentrer en
terme de timing pour le valider proprement.

Je te tiens au jus.



Le 8 oct. 2017 7:28 PM, "Arnaud Juracek" <notifications@github.com> a
écrit :

Peut-être en faisant un test de continuité sur des broches dispo du RJ ?
L'idée c'est vraiment d'avoir une info de branché/débranché, pour faciliter
le mapping (et la gestion des nodes < 4 strips).

Mais si ça te semble trop compliqué à mettre en place sur 4x23 RJ, je
trouverais une astuce sur la GUI pour que ça soit l'utilisateur qui entre
l'info.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Hemisphere-Project/stratum-hnode/issues/2#issuecomment-335022976>,
or mute the thread

**Comment by Maigre** [comment]
Il y aurait aussi  sûrement d'autres alternatives avec un peu
d'électronique mais on revient aux soucis de proto / PCB / pins du
microcontrolleur / timing de validation..
