### ISSUE TITLE
Handle disconnection err

### ISSUE THREAD

**Issue by arnaudjuracek** [Hemisphere-Project/stratum-hnode#3]
Sur le proto, quand l'app tourne et qu'on déconnecte une boîte, hnode throw cette erreur : 

```java
stratum-app/node_modules/hnode/Hnode/index.js:168
          if (err) throw err;
                   ^

Error: send EADDRNOTAVAIL 192.168.0.210:3738
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:402:11)
```

À wrapper dans un try...catch et emit un event d'erreur, pour permettre à l'app de gérer les déconnections intempestives.

@bubu : 
Le comportement désiré en cas de débranchement pendant l'install : 
- l'app continue de tourner (mais quatre strips ne s'allument plus) 
- le régisseur rebranche le node
- le signal raccroche

**Comment by arnaudjuracek** [comment]
Du coup à tester au moment de scale : vérifier comment hnode réagi si l'app lui demande d'envoyer un payload à une IP non dispo

**Comment by Maigre** [comment]
ok il faut que je mette le nez là dedans avant de mettre un try..catch:
normalement un envoi UDP n'est pas sensé planter si la destination n'est pas joignable.
C'est le router ou le switch qui est sensé drop le paquet si la destination est introuvable
mais c'est tout. Étrange donc.

**Comment by arnaudjuracek** [comment]
D'accord. 
Pour info pour le test proto je n'utilise pas de router ou de swtich, c'est directement mackbook <-> node.

**Comment by Maigre** [comment]
Ah du coup l'erreur se produit peut être plutôt lorsque  ton ordi perd la
connexion, et non lorsque une node perd la connexion. Dans ton cas ces 2
événement se produisent au même moment. Je pense à ca car j'avais testé la
perte de node et il n'y avait pas de soucis, ça raccrochait rapidement
ensuite. Mais je n'ai pas testé de débrancher l'ordi.
Je regarde ça et je te dis.

Le 19 oct. 2017 5:35 PM, "Arnaud Juracek" <notifications@github.com> a
écrit :

D'accord.
Pour info pour le test proto je n'utilise pas de router ou de swtich, c'est
directement mackbook <-> node.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/Hemisphere-Project/stratum-hnode/issues/3#issuecomment-337946822>,
or mute the thread

**Comment by Maigre** [comment]
c'était bien le soucis.
j'ai remplacé l'exception par un warning pour cette erreur.
++
